#!/bin/bash
# .bash_profile: 全ユーザーに適応される bash 設定ファイル

echo "Load ~/.bash_profile"

# XXenv
export PYENV_ROOT="$HOME/.pyenv"
export PATH="$PYENV_ROOT/bin:$PATH"

# Rust
source "$HOME/.cargo/env"

# Load ~/.bashrc
if [[ -f $HOME/.bashrc ]]; then
	source $HOME/.bashrc
fi
