#!/bin/bash

##### ENV #####

EDITOR=vim

##### PATH PRIORITY SETTINGS #####
#  Homebrew (sbin)
export PATH=/usr/local/sbin:$PATH
#  nodebrew
export PATH=$HOME/.nodebrew/current/bin:$PATH
#  golang
export PATH=/usr/local/opt/go/libexec/bin:$PATH
#  rust
export PATH="$HOME/.cargo/bin:$PATH"

##### ENV SETTINGS #####
# golang
export GOROOT="/usr/local/opt/go/libexec"
export GOPATH="${HOME}/.golang"

# ENV: Google Drive
export GOOGLE_DRIVE_ROOT="${HOME}/Google Drive"

# ENV: GUI Editor
export GUI_EDITOR="code"

# XXenv init 
for anyenv in "pyenv" "rbenv" "nodenv"; do
	if [[ -d "$HOME/.${anyenv}" ]]; then
		eval "$(${anyenv} init -)"
	fi
done

# ALIAS: pip
alias pip2='pip'
alias pip='pip3'

# Alias: ls
if type "colorls" > /dev/null 2>&1; then
	alias ls-old='/bin/ls -aG'
	alias ls='colorls -a'
	alias ll='colorls -al'
else
	alias ls='/bin/ls -Ga'
	alias ll='/bin/ls -Gal'
fi

# ALIAS: rsync (2.6.9 -> 3.1)
alias rsync='rsync3.1'

# ALIAS: vim
alias v='vim'

# ALIAS: git
alias g='git'

# ALIAS: tig
if type "tig" > /dev/null 2>&1; then
	alias t='tig --all'
fi

# ALIAS: docker
alias d='docker'
alias dc='docker-compose'

# ALIAS: ls | grep
alias lg='/bin/ls -a1 | grep'

# ALIAS: fzf-prev
alias fzf-prev="fzf --preview '[[ $(file --mime {}) =~ binary ]] && echo {} is a binary file || (highlight -O ansi {}) 2> /dev/null | head -500"
alias fv='fzf-prev'

# ALIAS: ghq
if type "ghq" > /dev/null 2>&1; then
	alias gg='ghq get'
	if type "fzf" > /dev/null 2>&1; then
		alias gcd='ghq look $(ghq list | fzf)'
		alias gls='ghq list | fzf'
	fi
fi

# ALIAS: .rc edit by VIM
alias bashrc="vim ~/.bashrc"
alias zshrc="vim ~/.zshrc"
alias vimrc="vim ~/.vimrc"
alias nvimrc="nvim ~/.config/nvim/init.vim"
alias gitconfig="vim ~/.gitconfig"

# ALIAS: .dotfiles Git Repository
alias dotfiles="cd ${HOME}/.dotfiles"

# ALIAS: PATH
alias PATH="echo $PATH | tr ':' '\n'"

# ALIAS: pkill
alias pkill="pkill -15"

# ALIAS: man -> .pdf -> open Skim.App
# REF: https://sourceforge.net/p/skim-app/wiki/Tips_and_Tricks/
# alias manp='man -t \!* | ps2pdf - /tmp/man_\!$.pdf && open -a Skim /tmp/man_\!$.pdf'
function manp () {
	if [ $# -lt 1 ]; then
		echo "manp: invalid arguments !"
		echo "usage: manp [man-name]"
	else
		man -t $1 | ps2pdf - /tmp/man_$1.pdf && open -a Skim /tmp/man_$1.pdf
	fi
}

function mkTexDoc () {
	DIR_NAME="${GOOGLE_DRIVE_ROOT}/情報学部/NewTexReport"
	PATH_RESOURCE="${GOOGLE_DRIVE_ROOT}/情報学部/.tex_resource"

	if [[ -e $DIR_NAME ]]; then
		echo "${DIR_NAME}: already exists !"
		subl "${DIR_NAME}" 
	else
		mkdir -v -p "$DIR_NAME/img"
		cp -v "${PATH_RESOURCE}/Preamble.tex" "${PATH_RESOURCE}/Source.tex" "$DIR_NAME/" 
		subl "${DIR_NAME}"
	fi
}

function mkSemiReport() {
	DIR_ROOT="${GOOGLE_DRIVE_ROOT}/情報学部/研究/Semi_Report"
	PATH_RESOURCE="${GOOGLE_DRIVE_ROOT}/情報学部/.tex_resource"

	NUM_OF_REPORT=$(find ${DIR_ROOT} -maxdepth 1 -type d | grep -E '.*/#[0-9]+$' | sed -E 's%'"${DIR_ROOT}"'/#%%g' | sort -r | head -1)
	# echo "NUM_OF_REPORT = ${NUM_OF_REPORT}"
	NUM_OF_REPORT=$(expr ${NUM_OF_REPORT} + 1)

	DIR_PATH="${DIR_ROOT}/#${NUM_OF_REPORT}"

	if [[ -e ${DIR_PATH} ]]; then
		echo "${DIR_PATH}: already exists !"
	else
		mkdir -v -p "${DIR_PATH}/img"
		cp -v "${PATH_RESOURCE}/Preamble.tex" "${PATH_RESOURCE}/SemiReport.tex" "${DIR_PATH}/" 
		subl "${DIR_PATH}"
	fi
}

function pdfFontEmbed() {
	if [ $# -lt 1 ]; then
		echo "pdfFontEmbed: invalid arguments !"
		echo "usage: pdfFontEmbed [pdf-file]"
	else
		OUT_NAME=$(echo -n $1 | sed -e 's#\.pdf#_embed.pdf#g')
		echo "$1  -->  Font Embed  -->  ${OUT_NAME}"
		gs -q -dNOPAUSE -dBATCH -dPDFSETTINGS=/prepress -sDEVICE=pdfwrite -sOutputFile=\"${OUT_NAME}\" \"$1\"
		pdffonts "${OUT_NAME}"
	fi
}

# less with Syntax-Highlight, Line-Number
export LESSOPEN='| /usr/local/bin/src-hilite-lesspipe.sh %s'
export LESS='-gj10 --no-init --quit-if-one-screen --RAW-CONTROL-CHARS -N'

# Customize for Skim.app
function SkimEnableAutoSave(){
	defaults write -app Skim SKAutosaveInterval -float 15.0
	echo "Skim: Enabled Auto-Saving (Interval = 15.0 sec)"
}

function SkimDisableAutoSave(){
	defaults write -app Skim SKAutosaveInterval -float 0.0
	echo "Skim: Disabled Auto-Saving"
}


# File Encrypt & Decrypt 
function myFileEncrypt {
	if [ $# -ne 1 ] ;then
		echo "usage: myFileEncrypt [file-to-encrypt]"
	else
		openssl aes-256-cbc -e -in "$1" -out "$1.encrypted"
	fi
}

function myFileDecrypt {
	if [ $# -ne 1 ] ;then
		echo "usage: myFileDecrypt [file-to-decrypt]"
	else
		openssl aes-256-cbc -d -in "$1" -out "${1/.encrypted/}"
	fi
}

function dockerToolboxInit {
	if [[ -d '/Applications/Docker/Docker Quickstart Terminal.app' ]]; then
		bash --login '/Applications/Docker/Docker Quickstart Terminal.app/Contents/Resources/Scripts/start.sh' 
	fi
}
