#!/usr/bin/env zsh

####################### zplug ###############################
source "${HOME}/.zplug/init.zsh"

zplug "sorin-ionescu/prezto"

zplug "b4b4r07/enhancd", use:init.sh

zplug "Tarrasch/zsh-autoenv"

zplug load 
# zplug load --verbose
####################### zplug ###############################


####################### prezto ###############################
# Override Prompt
function paradox_customize() {
	echo -ne $'%K{default} %(?::%F{196}✘ )%(!:%F{220}⚡ :)%(1j:%F{87}⚙ :)%F{yellow}%n%F{red}%B@%b%F{green}%m%b%f %F{blue}%{\e[7m%}\ue0b0%{\e[0m%}%K{blue}%F{255} %B$_prompt_paradox_pwd%b %K{green}%F{blue}%F{black} ${(e)git_info[ref]}${(e)git_info[status]} %k%F{green}%f'
}
PROMPT='${(e)$(paradox_customize)}'$'\n'' ${editor_info[keymap]} '

####################### prezto ###############################

# Enable: zsh-completions
if [ -e "/usr/local/share/zsh-completions" ]; then
    fpath=(/usr/local/share/zsh-completions $fpath)
fi
if [ -e "$HOME/.zsh/completions" ]; then
	fpath=($HOME/.zsh/completions $fpath)
fi

autoload -U compinit
compinit

# Enable: History of Directory
setopt auto_pushd
# Enable: Command Auto-Fixing
setopt correct
# Disable: 'no matches found'
setopt nonomatch
# Enable: Completion dotfiles
setopt globdots

# Customize: zsh-autosuggestion
ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE="fg=240"

# Customize: enhancd
ENHANCD_FILTER=fzf:fzy:peco

# Enable Vi-Edit Mode in ZLE(zsh-line-edit)
# REF: https://qiita.com/b4b4r07/items/8db0257d2e6f6b19ecb9
bindkey -v

# vi-cmd-mode を抜けるキーバインドを Ctrl-Q に変更
# REF: https://superuser.com/questions/351499/how-to-switch-comfortably-to-vi-command-mode-on-the-zsh-command-line
bindkey -M viins '^Q' vi-cmd-mode
bindkey -M viins '^A' beginning-of-line
bindkey -M viins '^K' kill-line
bindkey -M viins '^L' clear-screen
bindkey -M viins '^U' kill-whole-line


#################### Import from .bashrc #################
source ${HOME}/.bashrc
#################### Import from .bashrc #################


# ALIAS: Ghostscript
# zsh の gs='git stash'と干渉するため
alias gs='/usr/local/bin/gs'


# zsh-completion
if [[ ! -e "${HOME}/.zsh/completion" ]]; then
	mkdir -p "${HOME}/.zsh/completion"
fi

# Docker: zsh-completion
if [[ $(uname) == "Darwin" ]]; then
	DOCKER_APP_DIR="/Applications/Docker.app"
	ZSH_COMP_DIR="${HOME}/.zsh/completion"

	if [[ -e ${DOCKER_APP_DIR} ]]; then
		DOCKER_COMP_DIR="${DOCKER_APP_DIR}/Contents/Resources/etc"
		COMP_FILE_PREFIXES=("docker", "docker-compose", "docker-machine")

		for COMP_FILE_PREFIX in COMP_FILE_PREFIXES; do
			COMP_FILE_SRC="${DOCKER_COMP_DIR}/${COMP_FILE_PREFIX}.zsh-completion"
			COMP_FILE_DST="${ZSH_COMP_DIR}/_${COMP_FILE_PREFIX}"
			if [[ -e ${COMP_FILE_SRC} && ! -e ${COMP_FILE_DST} ]]; then
				ln -s ${COMP_FILE_SRC} ${COMP_FILE_DST}
			fi
		done
	fi
fi


# fzf を使って History 検索
function select-history-fzf() {
	if type "fzf" > /dev/null 2>&1; then
		BUFFER=$(history -n -r 1 | fzf --no-sort +m --query "$LBUFFER" --prompt="[History] > ")
		CURSOR=$#BUFFER
	else
		read -p "'fzf' is not found. Do you install 'fzf' from Homebrew [y/n] ? " answer < /dev/tty
		while [[ "$answer" != "y" && "$answer" != "n" ]]; do
			read -p "'Please input 'y' or 'n': " answer < /dev/tty
		done
		if [[ "$answer" == "y" ]]; then
			brew install fzf
		fi
	fi
}
# fzy を使って History 検索
function select-history-fzy() {
	if type "fzf" > /dev/null 2>&1; then
		BUFFER=$(history -n -r 1 | fzy --query "$LBUFFER" --prompt="[History] > ")
		CURSOR=$#BUFFER

		zle reset-prompt
	else
		read -p "'fzy' is not found. Do you install 'fzy' from Homebrew [y/n] ? " answer < /dev/tty
		while [[ "$answer" != "y" && "$answer" != "n" ]]; do
			read -p "'Please input 'y' or 'n': " answer < /dev/tty
		done
		if [[ "$answer" == "y" ]]; then
			brew install fzy
		fi
	fi
}
zle -N select-history-fzf
bindkey -M viins '^r' select-history-fzf

# ls -1 -> fzf -> open
function ls-fzf-open() {
	open $(find . -type f | fzf --prompt "OPEN FILE > " --preview '[[ $(file --mime {}) =~ binary ]] && echo {} is a binary file || (highlight -O ansi {}) 2> /dev/null | head -500' )
}
zle -N ls-fzf-open
bindkey -M viins '^f' ls-fzf-open


source ~/.zplug/repos/b4b4r07/enhancd/init.sh

test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"

export PATH="$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH"

