symlinks:
  - { src: ./shims/.bash,         dst: $HOME/.bash }
  - { src: ./shims/.bash_profile, dst: $HOME/.bash_profile }
  - { src: ./shims/.config,       dst: $HOME/.config }
  - { src: ./shims/.gitconfig,    dst: $HOME/.gitconfig }
  - { src: ./shims/.ipython,      dst: $HOME/.ipython }
  - { src: ./shims/.latexmkrc,    dst: $HOME/.latexmkrc }
  - { src: ./shims/.pdbrc,        dst: $HOME/.pdbrc }
  - { src: ./shims/.ptpython,     dst: $HOME/.ptpython }
  - { src: ./shims/.tigrc,        dst: $HOME/.tigrc }
  - { src: ./shims/.vim,          dst: $HOME/.vim }
  - { src: ./shims/.vimrc,        dst: $HOME/.vimrc }
  - { src: ./shims/.zplug,          dst: $HOME/.zplug }
  - { src: ./shims/.zsh,          dst: $HOME/.zsh }
  - { src: ./shims/.zshenv,       dst: $HOME/.zshenv }
  