version: '3'

tasks:
  default:
    - brew install sheldon
    - curl -L https://iterm2.com/shell_integration/zsh > {{ .TASKFILE_DIR }}/scripts/iterm2/shell_integration.zsh
    - sudo /bin/bash -c "echo export ZDOTDIR={{ .TASKFILE_DIR }} >> /etc/zshenv"
